
version: "3"

services:
  postgres:
    image: danielebert00/postgrestestedversion:1
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: danielebert00/keycloaktestedversion:1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  frontend1:
    build:
      context: ./frontend1
      dockerfile: ./Dockerfile
    image: danielebert00/reactfrontend3000:2
    ports:
      - "3000:3000"
  frontend2:
    build:
      context: ./frontend2
      dockerfile: ./Dockerfile
    image: danielebert00/reactfrontend3001:2
    ports:
      - "3001:3001"
  backendservice1:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    image: danielebert00/backendservice:2
    environment:
      client_ID: service1
      PORT: 5001
    ports:
      - "5001:5001"
  backendservice2:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    image: danielebert00/backendservice:2
    environment:
      client_ID: service2
      PORT: 5002
    ports:
      - "5002:5002"
